USE [master]
GO
/****** Object:  Database [db_taskManager_1036]    Script Date: 16-06-2026 11:43:04 ******/
CREATE DATABASE [db_taskManager_1036]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_taskManager_1036', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\db_taskManager_1036.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_taskManager_1036_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\db_taskManager_1036_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [db_taskManager_1036] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_taskManager_1036].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db_taskManager_1036] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [db_taskManager_1036] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_taskManager_1036] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_taskManager_1036] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET  ENABLE_BROKER 
GO
ALTER DATABASE [db_taskManager_1036] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_taskManager_1036] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [db_taskManager_1036] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [db_taskManager_1036] SET  MULTI_USER 
GO
ALTER DATABASE [db_taskManager_1036] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_taskManager_1036] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db_taskManager_1036] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db_taskManager_1036] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_taskManager_1036] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db_taskManager_1036] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [db_taskManager_1036] SET QUERY_STORE = ON
GO
ALTER DATABASE [db_taskManager_1036] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [db_taskManager_1036]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 16-06-2026 11:43:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tasks]    Script Date: 16-06-2026 11:43:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tasks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[Priority] [nvarchar](max) NOT NULL,
	[Status] [nvarchar](max) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[AssignedUserId] [int] NULL,
	[CreatedByUserId] [int] NOT NULL,
 CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 16-06-2026 11:43:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[PasswordHash] [nvarchar](max) NOT NULL,
	[Role] [nvarchar](max) NOT NULL,
	[RefreshToken] [nvarchar](max) NULL,
	[RefreshTokenExpiry] [datetime2](7) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Tasks_AssignedUserId]    Script Date: 16-06-2026 11:43:04 ******/
CREATE NONCLUSTERED INDEX [IX_Tasks_AssignedUserId] ON [dbo].[Tasks]
(
	[AssignedUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Tasks_CreatedByUserId]    Script Date: 16-06-2026 11:43:04 ******/
CREATE NONCLUSTERED INDEX [IX_Tasks_CreatedByUserId] ON [dbo].[Tasks]
(
	[CreatedByUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tasks]  WITH CHECK ADD  CONSTRAINT [FK_Tasks_Users_AssignedUserId] FOREIGN KEY([AssignedUserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Tasks] CHECK CONSTRAINT [FK_Tasks_Users_AssignedUserId]
GO
ALTER TABLE [dbo].[Tasks]  WITH CHECK ADD  CONSTRAINT [FK_Tasks_Users_CreatedByUserId] FOREIGN KEY([CreatedByUserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Tasks] CHECK CONSTRAINT [FK_Tasks_Users_CreatedByUserId]
GO
USE [master]
GO
ALTER DATABASE [db_taskManager_1036] SET  READ_WRITE 
GO
